GO
--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[Currency] ON

MERGE INTO [dbo].[Currency] AS Target
USING (VALUES
  (1,N'EUR')
 ,(2,N'USD')
 ,(3,N'GBP')
 ,(4,N'RON')
 ,(5,N'CAD')
) AS Source ([CurrencyID],[CurrencyCode])
ON (Target.[CurrencyID] = Source.[CurrencyID])
WHEN MATCHED AND (
	NULLIF(Source.[CurrencyCode], Target.[CurrencyCode]) IS NOT NULL OR NULLIF(Target.[CurrencyCode], Source.[CurrencyCode]) IS NOT NULL) THEN
 UPDATE SET
  [CurrencyCode] = Source.[CurrencyCode]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([CurrencyID],[CurrencyCode])
 VALUES(Source.[CurrencyID],Source.[CurrencyCode])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[Currency]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[Currency] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [dbo].[Currency] OFF
GO
SET NOCOUNT OFF
GO
